### ISSUE TITLE
Suite value missing in the CTRFTest return statement

### ISSUE THREAD

**Issue by pgs352** [ctrf-io/junit-to-ctrf#5]
Hi, 
Using this converter to go from behave-Junit .xmls to ctrf I found that the CTRFTest is returning info in a way that makes it difficult to visualize in the github-test-reporter. 

When returning the CTRF test case, I am missing the 'suite' info and also I noticed that the TC name should only be ${testCase.name}

Currently this return statement 
```
  return {
    name: `${testCase.suite}: ${testCase.name}`,
    status,
    duration: durationMs,
    message: testCase.failure || testCase.error ? (testCase.failure || testCase.error) : undefined,
    trace: testCase.failure || testCase.error ? (testCase.failure || testCase.error) : undefined,
  };
```

Should become like this : 
```
  return {
    name: `${testCase.name}`,
    status,
    duration: durationMs,
    message: testCase.failure || testCase.error ? (testCase.failure || testCase.error) : undefined,
    trace: testCase.failure || testCase.error ? (testCase.failure || testCase.error) : undefined,
    suite: `${testCase.suite}`,
  };
```

**Comment by Ma11hewThomas** [comment]
For test name you can now use[arg -u false](https://github.com/ctrf-io/junit-to-ctrf?tab=readme-ov-file#exclude-suite-name). 

If suite name exists the property will be included.

thanks for the feedback
